stages:
  - build image

build-image:
  stage: build image
  image: docker
  services:
    - docker:dind
  variables:
    DSFR_VERSION: "v1.13.0"
    DSFR_CHART_VERSION: "v1.0.0"
    SUPERSET_VERSION: "4.1.1"
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build --build-arg TAG_DSFR=$DSFR_VERSION \
                   --build-arg TAG_DSFR_CHART=$DSFR_CHART_VERSION \
                   --build-arg SUPERSET_VERSION=$SUPERSET_VERSION \
                   -t $CI_REGISTRY_IMAGE:$SUPERSET_VERSION -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$SUPERSET_VERSION
