stages:
  - build image

build-image:
  stage: build image
  image: docker
  services:
    - docker:dind
  variables:
    DSFR_VERSION: "1.13.0"
    DSFR_CHART_VERSION: "1.0.0"
    SUPERSET_REPO: "apache/superset"
    SUPERSET_VERSION: "4.1.1"
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - echo "DSFR_VERSION -- $DSFR_VERSION"
    - echo "DSFR_CHART_VERSION -- $DSFR_CHART_VERSION"
    - echo "SUPERSET_VERSION -- $SUPERSET_VERSION"
    - docker build -f Dockerfile --build-arg TAG_DSFR=${DSFR_VERSION} --build-arg TAG_DSFR_CHART=${DSFR_CHART_VERSION} --build-arg SUPERSET_VERSION=${SUPERSET_VERSION} -t $CI_REGISTRY_IMAGE:${SUPERSET_VERSION} .
    - docker push $CI_REGISTRY_IMAGE:$SUPERSET_VERSION
